"""End-to-end data EDA workflow and report artifact export."""

from __future__ import annotations

from dataclasses import dataclass, replace
from datetime import date, datetime
from contextlib import nullcontext
import json
from pathlib import Path
from typing import Any, Mapping

import polars as pl

from data.contract import ValidatedDataContract
from logger import get_logger
from preprocessing.cleaning import preprocess_data
from preprocessing.exploration import explore_dataset
from progress import ProgressReporter
from reporting.xlsx_report import write_eda_report

from .analytics import EdaAnalysisResult, build_eda_analysis


logger = get_logger(__name__)
_SUMMARY_LABELS = {
    "row_count": "原始样本数",
    "column_count": "原始字段数",
    "feature_count": "候选特征数",
    "candidate_feature_count": "候选特征数",
    "id_unique_rate": "主键唯一率",
    "date_parse_rate": "日期解析率",
    "bad_sample_count": "原始坏样本数",
    "target_bad_rate": "原始坏样本率",
    "bad_sample_rate": "原始坏样本率",
    "cleaned_row_count": "清洗后样本数",
    "cleaned_column_count": "清洗后字段数",
    "retained_feature_count": "保留特征数",
    "removed_duplicate_count": "去重样本数",
    "invalid_date_count": "无效日期数",
}


@dataclass(frozen=True)
class EdaRunResult:
    """Paths and in-memory results from one completed data EDA run."""

    output_dir: Path
    report_path: Path
    cleaned_data_path: Path
    analysis: EdaAnalysisResult


def _json_value(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if isinstance(value, float) and (value != value or value in (float("inf"), float("-inf"))):
        return None
    return value


def _table_payload(data: pl.DataFrame) -> dict[str, Any]:
    return {
        "headers": data.columns,
        "rows": [[_json_value(value) for value in row] for row in data.rows()],
    }


def _write_csv(data: pl.DataFrame, output_dir: Path, name: str) -> Path:
    path = output_dir / f"{name}.csv"
    data.write_csv(path)
    return path


def run_eda(
    data: pl.DataFrame,
    contract: ValidatedDataContract,
    output_dir: str | Path,
    *,
    node_executable: str = "node",
    progress: ProgressReporter | None = None,
    report_dir: str | Path | None = None,
    generate_report: bool = True,
    analysis_config: Mapping[str, Any] | None = None,
) -> EdaRunResult:
    """Clean confirmed data, calculate EDA tables, and export an Excel report.

    The workbook is generated by the portable XlsxWriter backend; no Node.js
    or Codex-specific report runtime is required.
    """
    run_dir = Path(output_dir).expanduser().resolve()
    run_dir.mkdir(parents=True, exist_ok=True)
    report_output_dir = (
        Path(report_dir).expanduser().resolve() if report_dir is not None else run_dir
    )
    report_output_dir.mkdir(parents=True, exist_ok=True)
    logger.info("Starting EDA run: %s", run_dir)
    cleaned_data_path = run_dir / "cleaned_data.parquet"
    payload_path = run_dir / "eda_report_payload.json"
    report_path = report_output_dir / "data_eda_report.xlsx"

    cleaning_stage = (
        progress.track(
            "eda-cleaning",
            running_summary="正在处理重复样本、无效日期和低质量字段",
            success_summary="数据清理完成",
            artifacts=[cleaned_data_path, run_dir / "column_decisions.csv"],
        )
        if progress
        else nullcontext()
    )
    with cleaning_stage:
        options = dict(analysis_config or {})
        cleaning = preprocess_data(
            data,
            contract,
            missing_rate_threshold=float(options.get("missing_rate_threshold", 0.8)),
            constant_rate_threshold=float(options.get("constant_rate_threshold", 0.8)),
            duplicate_strategy=str(options.get("duplicate_strategy", "keep_first")),
        )
        cleaning.data.write_parquet(cleaned_data_path)
        _write_csv(cleaning.column_decisions, run_dir, "column_decisions")

    eda_stage = (
        progress.track(
            "eda",
            running_summary="正在计算分布、分箱、相关性和月度稳定性",
            success_summary="探索性分析计算完成",
            artifacts=[run_dir / "eda_summary.json", payload_path],
        )
        if progress
        else nullcontext()
    )
    with eda_stage:
        raw_exploration = explore_dataset(data, contract)
        cleaned_contract = replace(contract, feature_cols=cleaning.feature_cols)
        analysis = build_eda_analysis(
            cleaning.data,
            cleaned_contract,
            month_col=str(options.get("month_col", "event_month")),
            bin_count=int(options.get("bin_count", 10)),
            ks_bucket=int(options.get("ks_bucket", options.get("bin_count", 10))),
            ks_method=str(options.get("ks_method", "quantile")),
            baseline_month=options.get("psi_base_month"),
            max_categories=int(options.get("max_categories", 20)),
            correlation_method=str(options.get("correlation_method", "pearson")),
            metrics_backend=str(options.get("metrics_backend", "toad")),
        )
        _write_csv(raw_exploration.column_profile, run_dir, "column_profile")
        _write_csv(analysis.univariate_overview, run_dir, "univariate_overview")
        _write_csv(analysis.binning_detail, run_dir, "binning_detail")
        _write_csv(analysis.monthly_sample, run_dir, "monthly_sample")
        _write_csv(analysis.monthly_psi, run_dir, "monthly_psi")
        _write_csv(analysis.monthly_discrimination, run_dir, "monthly_discrimination")
        _write_csv(analysis.ks_bucket, run_dir, "ks_bucket")
        _write_csv(analysis.correlation_pairs, run_dir, "correlation_pairs")

        summary = {
            **raw_exploration.summary,
            "cleaned_row_count": cleaning.data.height,
            "cleaned_column_count": cleaning.data.width,
            "retained_feature_count": len(cleaning.feature_cols),
            "removed_duplicate_count": cleaning.removed_duplicate_count,
            "invalid_date_count": cleaning.invalid_date_count,
        }
        (run_dir / "eda_summary.json").write_text(
            json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        payload = {
            "title": "风控数据 EDA 报告",
            "tables": {
                "1.数据概况": {
                    "headers": ["指标", "值"],
                    "rows": [
                        [_SUMMARY_LABELS.get(key, key), _json_value(value)]
                        for key, value in summary.items()
                    ],
                },
                "2.字段画像": _table_payload(raw_exploration.column_profile),
                "3.特征质量": _table_payload(cleaning.column_decisions),
                "4.单变量概览": _table_payload(analysis.univariate_overview),
                "5.分箱明细": _table_payload(analysis.binning_detail),
                "6.月度样本": _table_payload(analysis.monthly_sample),
                "7.稳定性PSI": _table_payload(analysis.monthly_psi),
                "8.相关性": _table_payload(analysis.correlation_pairs),
                "9.月度区分度": _table_payload(analysis.monthly_discrimination),
                "10.KS十分位": _table_payload(analysis.ks_bucket),
            },
        }
        payload_path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")

    if generate_report:
        logger.info("Generating EDA workbook: %s", report_path)
        report_stage = (
            progress.track(
                "eda-report",
                running_summary="正在生成 EDA Excel 报告",
                success_summary="EDA 报告已生成",
                artifacts=[report_path],
            )
            if progress
            else nullcontext()
        )
        with report_stage:
            write_eda_report(payload_path, report_path)
    elif progress:
        progress.emit("eda-report", "skipped", summary="未选择报告交付节点")
    logger.info("EDA run completed: %s", report_path)
    return EdaRunResult(run_dir, report_path, cleaned_data_path, analysis)
